"""Update habits and habit_entries tables

Revision ID: 575a676ddcff
Revises: ccfb5c2c9eb2
Create Date: 2026-04-01 18:02:53.567869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575a676ddcff'
down_revision: Union[str, Sequence[str], None] = 'ccfb5c2c9eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE occurance AS ENUM ('daily', 'weekly', 'monthly')")
    op.execute("CREATE TYPE habittype AS ENUM ('binary', 'duration', 'numeric')")
    op.add_column('habit_entries', sa.Column('value', sa.Integer(), nullable=True))
    op.add_column('habit_entries', sa.Column('note', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('occurance', sa.Enum('daily', 'weekly', 'monthly', name='occurance'), nullable=False))
    op.add_column('habits', sa.Column('frequency', sa.Integer(), nullable=False))
    op.add_column('habits', sa.Column('habit_type', sa.Enum('binary', 'duration', 'numeric', name='habittype'), nullable=False))
    op.add_column('habits', sa.Column('target_value', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_habits_habit_type'), 'habits', ['habit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habits_habit_type'), table_name='habits')
    op.drop_column('habits', 'target_value')
    op.drop_column('habits', 'habit_type')
    op.drop_column('habits', 'frequency')
    op.drop_column('habits', 'occurance')
    op.drop_column('habit_entries', 'note')
    op.drop_column('habit_entries', 'value')
    op.execute("DROP TYPE habittype")
    op.execute("DROP TYPE occurance")
    # ### end Alembic commands ###
